language: java

before_script:
  - cd src/main/resources/UI
  - npm update npm -g
  - npm install
  - npm run build
  - cd ../../../..

script:
  - mvn clean install
  
after_success:
  - mvn clean cobertura:cobertura coveralls:report